### ISSUE TITLE
Some questions about a 'layer normalization' on a decoder up-sampling layer.

### ISSUE THREAD

**Issue by WonwoongCho** [NVlabs/MUNIT#32]
Hi, I have some questions about the layer normalization used on the model.
why do you use the LN on a decoder?

I guess the reason is for making training stable.
Am I right..?

Additionally,
following lots of papers concerning a 'style transfer', the effect of the IN is flattening the style of the image. (That's why some networks of yours don't take normalization. )
But I don't know the high level view of the LN. Different from the IN, LN keeps the difference between channels. It means we can get a normalized feature without a loss of style through LN.

Is it right interpretation?
I wish your insightful comments.

Thanks.

**Comment by xunhuang1995** [comment]
I agree with your interpretation. In practice I observe LN can preserve style better than IN. Also, BN is not suited for our experiments since our batch size is small. For the two reasons we choose LN.

If the weight initialization is reasonable, it's also fine to not use normalization in up-sampling layers.
